### ISSUE TITLE
Errorf seems to have lost the original error embedded with %w

### ISSUE THREAD

**Issue by hyacinthus** [samber/oops#20]
In this case, `errors.Is` and `errors.As` won't work properly.

Furthermore, after discovering that `Wrap` and `Errorf` wrapped an error, it should be determined whether it is an `OopsError`. If it is, wouldn't it be better to join the context?

**Comment by samber** [comment]
The context is joined lazily with a recursive chain traversal, eg when `LogValuer` gets called.

I don't think we need unnecessary processing until the error is rendered.

I just made a fix for `errors.Is` and `errors.As` in the context of `oops.Errorf(...)`

**Comment by hyacinthus** [comment]
Thank you for your quick fix. It makes sense about "unnecessary processing".
